import type { CharacterCard, Rarity } from "./types";

const CARD_WIDTH = 1200;
const CARD_HEIGHT = 675;

const rarityColors: Record<Rarity, string> = {
  N: "#9ca3af",
  R: "#60a5fa",
  SR: "#c084fc",
  SSR: "#facc15",
};

export function renderPlaceholder(canvas: HTMLCanvasElement): void {
  const ctx = canvas.getContext("2d");
  if (!ctx) return;

  canvas.width = CARD_WIDTH;
  canvas.height = CARD_HEIGHT;

  ctx.fillStyle = "#111827";
  ctx.fillRect(0, 0, CARD_WIDTH, CARD_HEIGHT);

  ctx.fillStyle = "#ffffff";
  ctx.font = "bold 42px sans-serif";
  ctx.textAlign = "center";
  ctx.fillText("RPG STATUS MAKER", CARD_WIDTH / 2, 300);

  ctx.font = "28px sans-serif";
  ctx.fillStyle = "#d1d5db";
  ctx.fillText("画像を選択して、ステータスカードを生成してください", CARD_WIDTH / 2, 360);

  ctx.textAlign = "left";
}

export function renderCard(
  canvas: HTMLCanvasElement,
  image: HTMLImageElement,
  card: CharacterCard,
): void {
  const ctx = canvas.getContext("2d");
  if (!ctx) return;

  canvas.width = CARD_WIDTH;
  canvas.height = CARD_HEIGHT;

  drawBackground(ctx, card.rarity);
  drawFrame(ctx, card.rarity);
  drawImageArea(ctx, image, card.rarity);
  drawTexts(ctx, card);
}

function drawBackground(ctx: CanvasRenderingContext2D, rarity: Rarity): void {
  const gradient = ctx.createLinearGradient(0, 0, CARD_WIDTH, CARD_HEIGHT);

  gradient.addColorStop(0, "#111827");
  gradient.addColorStop(0.55, "#1f2937");
  gradient.addColorStop(1, "#030712");

  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, CARD_WIDTH, CARD_HEIGHT);

  const color = rarityColors[rarity];

  ctx.fillStyle = `${color}22`;
  ctx.beginPath();
  ctx.arc(1000, 120, 220, 0, Math.PI * 2);
  ctx.fill();

  ctx.fillStyle = `${color}14`;
  ctx.beginPath();
  ctx.arc(160, 620, 260, 0, Math.PI * 2);
  ctx.fill();
}

function drawFrame(ctx: CanvasRenderingContext2D, rarity: Rarity): void {
  const frameColor = rarityColors[rarity];

  ctx.lineWidth = 8;
  ctx.strokeStyle = frameColor;
  roundedRectPath(ctx, 24, 24, CARD_WIDTH - 48, CARD_HEIGHT - 48, 28);
  ctx.stroke();

  ctx.lineWidth = 2;
  ctx.strokeStyle = "#ffffff55";
  roundedRectPath(ctx, 44, 44, CARD_WIDTH - 88, CARD_HEIGHT - 88, 20);
  ctx.stroke();
}

function drawImageArea(
  ctx: CanvasRenderingContext2D,
  image: HTMLImageElement,
  rarity: Rarity,
): void {
  const x = 70;
  const y = 120;
  const width = 410;
  const height = 480;

  ctx.fillStyle = "#00000066";
  roundedRectPath(ctx, x + 10, y + 10, width, height, 22);
  ctx.fill();

  drawCoverImage(ctx, image, x, y, width, height, 22);

  ctx.lineWidth = 5;
  ctx.strokeStyle = rarityColors[rarity];
  roundedRectPath(ctx, x, y, width, height, 22);
  ctx.stroke();
}

function drawTexts(ctx: CanvasRenderingContext2D, card: CharacterCard): void {
  const rarityColor = rarityColors[card.rarity];

  ctx.fillStyle = "#ffffff";
  ctx.font = "bold 42px sans-serif";
  ctx.fillText("RPG STATUS CARD", 70, 82);

  ctx.fillStyle = rarityColor;
  ctx.font = "bold 52px sans-serif";
  ctx.textAlign = "right";
  ctx.fillText(card.rarity, 1120, 86);
  ctx.textAlign = "left";

  const infoX = 535;

  ctx.fillStyle = "#ffffff";
  drawFitText(ctx, `名前：${card.name}`, infoX, 150, 560, 36, 24, "bold");

  ctx.fillStyle = "#d1d5db";
  drawFitText(ctx, `職業：${card.job}`, infoX, 200, 560, 30, 22, "bold");

  ctx.fillStyle = "#fef3c7";
  ctx.font = "bold 28px sans-serif";
  ctx.fillText(`属性：${card.element}`, infoX, 250);

  ctx.fillStyle = "#ffffff";
  ctx.font = "bold 30px sans-serif";
  ctx.fillText("STATUS", infoX, 315);

  const statX = infoX;
  const statStartY = 365;
  const statGap = 48;

  drawStatBar(ctx, "HP", card.status.hp, statX, statStartY + statGap * 0);
  drawStatBar(ctx, "MP", card.status.mp, statX, statStartY + statGap * 1);
  drawStatBar(ctx, "攻撃", card.status.attack, statX, statStartY + statGap * 2);
  drawStatBar(ctx, "防御", card.status.defense, statX, statStartY + statGap * 3);
  drawStatBar(ctx, "素早さ", card.status.speed, statX, statStartY + statGap * 4);
  drawStatBar(ctx, "知力", card.status.intelligence, statX, statStartY + statGap * 5);

  const skillX = 855;
  const skillY = 315;

  ctx.fillStyle = "#ffffff";
  ctx.font = "bold 30px sans-serif";
  ctx.fillText("SKILL", skillX, skillY);

  ctx.font = "24px sans-serif";
  ctx.fillStyle = "#e5e7eb";

  card.skills.forEach((skill, index) => {
    drawFitText(ctx, `・${skill}`, skillX, skillY + 50 + index * 45, 220, 24, 16, "normal");
  });

  ctx.fillStyle = "#9ca3af";
  ctx.font = "20px sans-serif";
  ctx.textAlign = "right";
  ctx.fillText("Generated by RPG Status Maker", 1120, 625);
  ctx.textAlign = "left";
}

function drawStatBar(
  ctx: CanvasRenderingContext2D,
  label: string,
  value: number,
  x: number,
  y: number,
): void {
  const barX = x + 90;
  const barY = y - 23;
  const barWidth = 170;
  const barHeight = 22;
  const maxValue = 120;
  const rate = Math.min(value / maxValue, 1);

  ctx.fillStyle = "#e5e7eb";
  ctx.font = "24px sans-serif";
  ctx.fillText(label, x, y);

  ctx.fillStyle = "#374151";
  roundedRectPath(ctx, barX, barY, barWidth, barHeight, 10);
  ctx.fill();

  ctx.fillStyle = "#34d399";
  roundedRectPath(ctx, barX, barY, barWidth * rate, barHeight, 10);
  ctx.fill();

  ctx.fillStyle = "#ffffff";
  ctx.font = "22px sans-serif";
  ctx.fillText(String(value), barX + barWidth + 18, y);
}

function drawCoverImage(
  ctx: CanvasRenderingContext2D,
  image: HTMLImageElement,
  x: number,
  y: number,
  width: number,
  height: number,
  radius: number,
): void {
  const imageRatio = image.width / image.height;
  const areaRatio = width / height;

  let sourceX = 0;
  let sourceY = 0;
  let sourceWidth = image.width;
  let sourceHeight = image.height;

  if (imageRatio > areaRatio) {
    sourceWidth = image.height * areaRatio;
    sourceX = (image.width - sourceWidth) / 2;
  } else {
    sourceHeight = image.width / areaRatio;
    sourceY = (image.height - sourceHeight) / 2;
  }

  ctx.save();

  roundedRectPath(ctx, x, y, width, height, radius);
  ctx.clip();

  ctx.drawImage(
    image,
    sourceX,
    sourceY,
    sourceWidth,
    sourceHeight,
    x,
    y,
    width,
    height,
  );

  ctx.restore();
}

function drawFitText(
  ctx: CanvasRenderingContext2D,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  maxFontSize: number,
  minFontSize: number,
  weight: "normal" | "bold",
): void {
  let fontSize = maxFontSize;

  while (fontSize > minFontSize) {
    ctx.font = `${weight} ${fontSize}px sans-serif`;

    if (ctx.measureText(text).width <= maxWidth) {
      break;
    }

    fontSize -= 1;
  }

  ctx.fillText(text, x, y);
}

function roundedRectPath(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  width: number,
  height: number,
  radius: number,
): void {
  const r = Math.min(radius, width / 2, height / 2);

  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + width - r, y);
  ctx.quadraticCurveTo(x + width, y, x + width, y + r);
  ctx.lineTo(x + width, y + height - r);
  ctx.quadraticCurveTo(x + width, y + height, x + width - r, y + height);
  ctx.lineTo(x + r, y + height);
  ctx.quadraticCurveTo(x, y + height, x, y + height - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}